<a href="https://colab.research.google.com/github/Vga18/diplomado/blob/main/Proyecto_diplomado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Cont-AI**

## **Planteamiento del problema**

El desarrollo de pólizas es un proceso automático y tardado, ya que requiere tener un criterio para decidir que gastos van su cuenta contable

Plataforma de usuario para agilizar la capturación de pólizas de egresos

Acotado a las facturas XML-CFDI recibidas, y al catalogo de cuentas contables que maneja el Sistema Aspel COI versión 9

## Librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


pd.set_option("display.max_columns",200)
pd.set_option("display.max_rows",100)

## Funciones Auxiliares

## Datos

In [2]:
catalogo = pd.read_csv(r"/content/Datos/catalogo de cuentas contables.csv")
polizas22 = pd.read_csv(r"/content/Datos/polizas22.csv")
polizas23 = pd.read_csv(r"/content/Datos/polizas23.csv")
polizas24 = pd.read_csv(r"/content/Datos/polizas24.csv")
polizas25 = pd.read_csv(r"/content/Datos/polizas25.csv")
polizas26 = pd.read_csv(r"/content/Datos/polizas26.csv")

## Ingenieria

In [5]:
catalogo.tail(3)

,NUM_CTA,STATUS,TIPO,NOMBRE,NIVEL,NATURALEZA
301,610005700000000000002,A,D,EQUIPO DE SEGURIDAD,2,0
303,122000400000000000002,A,D,ISR RETENIDO,2,0
307,111000200000000000002,A,D,TAG CUENTA.0002706454,2,0

Ya que el objetivo es la clasificación de numero de cuentas se eligira ciertas variables

In [4]:
catalogo = catalogo[["NUM_CTA","STATUS","TIPO","NOMBRE","NIVEL","NATURALEZA"]]
catalogo = catalogo[catalogo['NIVEL'] != 3]
catalogo.sample(5)

,NUM_CTA,STATUS,TIPO,NOMBRE,NIVEL,NATURALEZA
13,117000000000000000001,A,A,DEUDORES DIVERSOS,1,0
115,410000300000000000002,A,D,VENTAS EXENTAS I.V.A.,2,1
20,118000300000000000002,A,D,SUBSIDIO AL EMPLEO,2,0
259,740000200000000000002,A,D,OTROS GASTOS,2,0
15,117000200000000000002,A,A,SOCIOS Y ACCIONISTAS,2,0

In [9]:
display(polizas26.head(5))

,TIPO_POLI,NUM_POLIZ,NUM_PART,PERIODO,EJERCICIO,NUM_CTA,FECHA_POL,CONCEP_PO,DEBE_HABER,MONTOMOV,NUMDEPTO,TIPCAMBIO,CONTRAPAR,ORDEN,CCOSTOS,CGRUPOS,IDINFADIPAR,IDUUID
0,Eg,1,1.0,1,2026,610004200000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-6315210, OPERADORA CONCESION...",D,994.83,0,1.0,0,1,0,0,-1,-1
1,Eg,1,2.0,1,2026,120000100000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-6315210, OPERADORA CONCESION...",D,159.17,0,1.0,0,2,0,0,-1,-1
2,Eg,1,3.0,1,2026,111000200000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-6315210, OPERADORA CONCESION...",H,1154.00,0,1.0,0,3,0,0,-1,-1
3,Eg,2,1.0,1,2026,610004200000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-1760426, CONCESIONARIA MEXIQ...",D,200.00,0,1.0,0,1,0,0,-1,-1
4,Eg,2,2.0,1,2026,120000100000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-1760426, CONCESIONARIA MEXIQ...",D,32.00,0,1.0,0,2,0,0,-1,-1

In [10]:
variables_destables = ["TIPO_POLI","PERIODO","NUM_CTA","FECHA_POL","CONCEP_PO","DEBE_HABER"]

Polizas22 = polizas22[variables_destables]
Polizas23 = polizas23[variables_destables]
Polizas24 = polizas24[variables_destables]
Polizas25 = polizas25[variables_destables]
polizas26 = polizas26[variables_destables]

polizas26.head(5)

,TIPO_POLI,PERIODO,NUM_CTA,FECHA_POL,CONCEP_PO,DEBE_HABER
0,Eg,1,610004200000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-6315210, OPERADORA CONCESION...",D
1,Eg,1,120000100000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-6315210, OPERADORA CONCESION...",D
2,Eg,1,111000200000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-6315210, OPERADORA CONCESION...",H
3,Eg,1,610004200000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-1760426, CONCESIONARIA MEXIQ...",D
4,Eg,1,120000100000000000002,2026-01-01 00:00:00.000,"PAGO FACTURA NO.T-1760426, CONCESIONARIA MEXIQ...",D